### ISSUE TITLE
Bosh Kala Shrine Freeze

### ISSUE THREAD

**Issue by sonofskywalker3** [CEObrainz/Second-Wind-Switch#1]
I don't know whether this happens on other versions, because I've only tried on the Switch, but I get a freeze and crash any time I try to enter the Bosh Kala Shrine. I'm running Atmosphere 1.2.5 on Horizon 10.0.4. (I can update the FW if needed, but I haven't had a reason to yet)

When I attempt to enter the shrine it goes to the loading screen, gets about 1/4 of the way through the loading icon, and then freezes for about a minute. After that it says the software was closed because of an error. I tried it on SXOS as well, and it immediately crashes without the freeze. If I open the game without the mod I can enter the shrine.

I used BCML to install the mod to my dumped version of the game, and then exported to .zip and unzipped into Atmosphere/contents. 

Please let me know if there's any other info you need, I'd love to try out the updated shrine.

**Comment by ghost** [comment]
+1 I'm having this same issue with this one shrine using BCML to install.
Atmosphère 1.2.5
HOS 13.2.0
BOTW 1.6.0
Second Wind v1.9.10

**Comment by CEObrainz** [comment]
Will be fixed in 1.9.10a
