### ISSUE TITLE
Some of the Ancient Trials Bosses are invisible.

### ISSUE THREAD

**Issue by ImJustSofa** [CEObrainz/Second-Wind-Switch#2]
"In the Ancient Trials, boss #2 was invisible. I actually thought that was the design, and it wasn't too bad to fight.

Boss #3 (Talus Lord) is also invisible, and that's pretty much impossible for me to grind through.

Running Nintendo Switch, FW 13.1, AMS 1.2.5, only SW mod running."

Steps to Reproduce:
1. Follow Torphedo's tutorial, walk up to boss.

Reported by lilloiswitterzee#677

![2022010311075300 - Vivek Mano](https://user-images.githubusercontent.com/73972388/147979827-59d4dc52-bf33-4e10-b69b-136385f64002.jpg)
9

**Comment by Nitr4m12** [comment]
Fixed in the latest stable release
