### ISSUE TITLE
A crash can occur when dying during the Knight of Ordon quest

### ISSUE THREAD

**Issue by ImJustSofa** [CEObrainz/Second-Wind-Switch#4]
"If I die during the fights for Rakib’s quest, the game crashes. It happened both after dying in the second stage and third stage. "

Steps to Repro:
Get to the part in the Knight of Ordon questline where waves of enemy need to be killed, and die.

Reported by aphtoris#4179

**Comment by Nitr4m12** [comment]
Fixed in the latest stable
